import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  section: {
    marginBottom: 20,
  },
  text: {
    fontSize: 12,
    lineHeight: 1.5,
  },
  scoreBox: {
    backgroundColor: '#f0f0f0',
    padding: 20,
    marginBottom: 20,
    textAlign: 'center',
  },
  scoreText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#059669',
  },
});

interface SimpleAssessmentPDFProps {
  assessment: {
    id: number;
    title: string;
    score: number;
    completedOn: string;
    recommendations?: string;
    survey?: {
      title: string;
    };
  };
}

export const SimpleAssessmentPDF: React.FC<SimpleAssessmentPDFProps> = ({ assessment }) => {
  const score = assessment.score || 0;
  const completedDate = new Date(assessment.completedOn || new Date()).toLocaleDateString();
  
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>AI Readiness Assessment Report</Text>
        
        <View style={styles.section}>
          <Text style={styles.text}>
            Assessment: {assessment.survey?.title || assessment.title}
          </Text>
          <Text style={styles.text}>
            Completed: {completedDate}
          </Text>
        </View>

        <View style={styles.scoreBox}>
          <Text style={styles.scoreText}>{(score / 10).toFixed(1)}/10</Text>
        </View>

        {assessment.recommendations && (
          <View style={styles.section}>
            <Text style={[styles.text, { fontWeight: 'bold', marginBottom: 10 }]}>
              AI Recommendations:
            </Text>
            <Text style={styles.text}>
              {assessment.recommendations.substring(0, 1000)}
              {assessment.recommendations.length > 1000 && '...'}
            </Text>
          </View>
        )}

        <View style={styles.section}>
          <Text style={[styles.text, { fontSize: 10, color: '#666' }]}>
            Generated by MyZone AI • Assessment ID: {assessment.id}
          </Text>
        </View>
      </Page>
    </Document>
  );
};