import React from "react";
import {
  Html,
  Head,
  Preview,
  Body,
  Container,
  Section,
  Img,
  Text,
  Button,
  Hr,
} from "@react-email/components";

interface AssessmentCompleteEmailProps {
  userEmail: string;
  assessmentTitle: string;
  score: number;
  pdfDownloadUrl: string;
  isGuest?: boolean;
}

export default function AssessmentCompleteEmail({
  userEmail,
  assessmentTitle,
  score,
  pdfDownloadUrl,
  isGuest = false,
}: AssessmentCompleteEmailProps) {
  const baseUrl = process.env.VITE_APP_URL || "https://your-app.replit.app";
  
  return (
    <Html>
      <Head />
      <Preview>Your AI Readiness Assessment Results are Ready!</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={logoSection}>
            <Text style={logoText}>MyZone AI</Text>
          </Section>
          
          <Section style={content}>
            <Text style={heading}>Your Assessment is Complete! 🎉</Text>
            
            <Text style={paragraph}>
              Hello{isGuest ? "" : ` ${userEmail}`},
            </Text>
            
            <Text style={paragraph}>
              Great news! Your AI readiness assessment "<strong>{assessmentTitle}</strong>" 
              has been completed and your personalized report is ready.
            </Text>
            
            <Section style={scoreSection}>
              <Text style={scoreText}>Your AI Readiness Score</Text>
              <Text style={scoreNumber}>{(score / 10).toFixed(1)}/10</Text>
            </Section>
            
            <Text style={paragraph}>
              Your comprehensive assessment report includes:
            </Text>
            
            <Text style={bulletPoint}>✓ Detailed score breakdown by category</Text>
            <Text style={bulletPoint}>✓ AI-powered personalized recommendations</Text>
            <Text style={bulletPoint}>✓ Industry benchmarking insights</Text>
            <Text style={bulletPoint}>✓ Actionable next steps for your organization</Text>
            
            <Section style={buttonSection}>
              <Button style={downloadButton} href={pdfDownloadUrl}>
                Download Your PDF Report
              </Button>
            </Section>
            
            {!isGuest && (
              <Text style={paragraph}>
                You can also view your results and all your previous assessments in your 
                <a href={`${baseUrl}/dashboard`} style={link}> dashboard</a>.
              </Text>
            )}
            
            <Hr style={hr} />
            
            <Text style={footer}>
              This report was generated by MyZone AI's assessment platform. 
              If you have any questions about your results, please don't hesitate to reach out.
            </Text>
            
            <Text style={footer}>
              <strong>MyZone AI Team</strong><br />
              Helping organizations navigate their AI readiness journey
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
}

const main = {
  backgroundColor: "#f6f9fc",
  fontFamily: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif',
  padding: "20px 0",
};

const container = {
  backgroundColor: "#ffffff",
  margin: "0 auto",
  padding: "20px 0 48px",
  marginBottom: "64px",
  maxWidth: "600px",
  borderRadius: "8px",
  boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
};

const logoSection = {
  padding: "32px 40px 0",
  textAlign: "center" as const,
};

const logoText = {
  fontSize: "24px",
  fontWeight: "bold",
  color: "#1a365d",
  margin: "0",
};

const content = {
  padding: "24px 40px",
};

const heading = {
  fontSize: "24px",
  lineHeight: "1.4",
  fontWeight: "600",
  color: "#1a202c",
  margin: "0 0 24px 0",
  textAlign: "center" as const,
};

const paragraph = {
  fontSize: "16px",
  lineHeight: "1.6",
  color: "#4a5568",
  margin: "0 0 16px 0",
};

const bulletPoint = {
  fontSize: "14px",
  lineHeight: "1.6",
  color: "#4a5568",
  margin: "0 0 8px 0",
  paddingLeft: "16px",
};

const scoreSection = {
  backgroundColor: "#f7fafc",
  padding: "24px",
  borderRadius: "8px",
  textAlign: "center" as const,
  margin: "24px 0",
};

const scoreText = {
  fontSize: "16px",
  fontWeight: "600",
  color: "#2d3748",
  margin: "0 0 8px 0",
};

const scoreNumber = {
  fontSize: "36px",
  fontWeight: "bold",
  color: "#1a365d",
  margin: "0",
};

const buttonSection = {
  textAlign: "center" as const,
  margin: "32px 0",
};

const downloadButton = {
  backgroundColor: "#1a365d",
  borderRadius: "6px",
  color: "#ffffff",
  fontSize: "16px",
  fontWeight: "600",
  textDecoration: "none",
  textAlign: "center" as const,
  display: "inline-block",
  padding: "12px 24px",
  border: "none",
  cursor: "pointer",
};

const link = {
  color: "#1a365d",
  textDecoration: "underline",
};

const hr = {
  borderColor: "#e2e8f0",
  margin: "32px 0",
};

const footer = {
  color: "#718096",
  fontSize: "14px",
  lineHeight: "1.6",
  margin: "0 0 16px 0",
};