import React from "react";
import { Document, Page, Text, View, Image } from "@react-pdf/renderer";
import { formatDate, getRadarChartData } from "@/lib/utils";
import styles from "./styles";
import RadarChart from "./radar";
import { getReadinessLevel } from "./utils";
import type { RecommendationsV2 } from "@shared/schema";

// V2 PDF component for structured JSON recommendations
export const AssessmentPDFV2 = ({
  assessment,
  logoUrl,
}: {
  assessment: any;
  logoUrl: string;
}) => {
  const { answers = [], survey = {}, recommendations } = assessment;
  const { title: surveyTitle } = survey;
  const score = assessment.score || 0;
  const recommendationsData = recommendations as RecommendationsV2;

  const readinessLevel = getReadinessLevel(score);
  const today = new Date();
  const year = today.getFullYear();
  const chartData = getRadarChartData(assessment);
  const logoPath = logoUrl || "@/assets/logo-keeran-ai.png";

  // Calculate total pages: Cover + Results + Intro + Categories (grouped 2 per page) + Outro + Responses
  const categoryPages = Math.ceil((recommendationsData.categories?.length || 0) / 2);
  const answerPages = Math.ceil(answers.length / 10);
  const totalPages = 2 + 1 + categoryPages + 1 + answerPages; // cover + results + intro + categories + outro + responses

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={styles.coverPage}>
        <View style={styles.logoContainer}>
          <Image src={logoPath} style={styles.logoBox} />
        </View>

        <View style={{ flex: 1, justifyContent: "center" }}>
          <Text style={styles.title}>AI Readiness Assessment Results</Text>
          {surveyTitle && (
            <Text style={styles.subtitle}>Based on: {surveyTitle}</Text>
          )}

          <View style={styles.contentBox}>
            <Text style={styles.scoreText}>Score: {score / 10} / 10</Text>
            <View style={styles.divider} />
            <Text style={styles.dateText}>
              Report generated on: {formatDate(today)}
            </Text>
          </View>
        </View>

        <Text style={styles.coverFooter}>
          Generated by Keeran Networks · AI Readiness Framework
        </Text>
      </Page>

      {/* Results Page */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Image src={logoPath} style={styles.logoBoxSmall} />
          <Text style={styles.headerTitle}>Assessment Results</Text>
        </View>

        <Text style={styles.sectionTitle}>AI Readiness Score</Text>
        <Text style={styles.sectionSubtitle}>
          Based on your responses, your organization is at the {readinessLevel}{" "}
          stage of AI readiness.
        </Text>

        {chartData && chartData.length > 0 ? (
          <View>
            <RadarChart data={chartData} />
            <Text style={styles.chartCaption}>
              This radar chart shows your organization's score across different
              dimensions of AI readiness.
            </Text>
            <Text style={styles.chartCaption}>
              Higher scores (closer to the edges) indicate greater maturity in
              that category.
            </Text>
          </View>
        ) : (
          <View style={styles.chartPlaceholder}>
            <Text style={styles.chartText}>Chart visualization</Text>
          </View>
        )}

        <View style={styles.footer}>
          <Text style={styles.pageNumber}>© {year} Keeran Networks</Text>
          <Text style={styles.pageNumber}>Page 2 of {totalPages}</Text>
        </View>
      </Page>

      {/* Intro Page */}
      {recommendationsData?.intro && (
        <Page size="A4" style={styles.page}>
          <View style={styles.header}>
            <Image src={logoPath} style={styles.logoBoxSmall} />
            <Text style={styles.headerTitle}>Executive Summary</Text>
          </View>

          <Text style={styles.sectionTitle}>
            AI Readiness Assessment Overview
          </Text>
          <Text style={styles.sectionSubtitle}>
            Based on your assessment score of {score / 10}/10 and insights
            from "MyZone AI Blueprint"
          </Text>

          <View style={{ marginTop: 20 }}>
            <Text style={{ fontSize: 11, lineHeight: 1.6, color: "#374151" }}>
              {recommendationsData.intro}
            </Text>
          </View>

          <View style={styles.footer}>
            <Text style={styles.pageNumber}>© {year} Keeran Networks</Text>
            <Text style={styles.pageNumber}>Page 3 of {totalPages}</Text>
          </View>
        </Page>
      )}

      {/* Category Pages (2 categories per page) */}
      {recommendationsData?.categories && (() => {
        const categories = recommendationsData.categories;
        const pages = [];
        
        for (let i = 0; i < categories.length; i += 2) {
          const pageCategories = categories.slice(i, i + 2);
          const pageNum = 4 + Math.floor(i / 2);

          pages.push(
            <Page key={`category-page-${i}`} size="A4" style={styles.page}>
              <View style={styles.header}>
                <Image src={logoPath} style={styles.logoBoxSmall} />
                <Text style={styles.headerTitle}>Category Analysis</Text>
              </View>

              {pageCategories.map((category, idx) => (
                <View key={`category-${i + idx}`} style={{ marginBottom: 20 }}>
                  <Text style={styles.sectionTitle}>
                    {category.title || category.name}
                  </Text>

                  <Text style={{ fontSize: 10, lineHeight: 1.5, color: "#374151", marginBottom: 12 }}>
                    {category.description}
                  </Text>

                  {/* Performance Metrics */}
                  {category.performance && (
                    <View style={{ marginBottom: 12, padding: 12, backgroundColor: "#F9FAFB", borderRadius: 4 }}>
                      <Text style={{ fontSize: 10, fontWeight: "bold", marginBottom: 6 }}>
                        How You Performed
                      </Text>
                      <Text style={{ fontSize: 9, marginBottom: 3 }}>
                        • Current Score: {category.performance.currentScore} / 10 ({Math.round(category.performance.currentScore * 10)}%)
                      </Text>
                      {category.performance.benchmark !== null && category.performance.benchmark !== undefined && (
                        <Text style={{ fontSize: 9, marginBottom: 3 }}>
                          • Benchmark: {category.performance.benchmark} / 10 ({Math.round(category.performance.benchmark * 10)}%)
                        </Text>
                      )}
                      {category.performance.trend && (
                        <Text style={{ fontSize: 9 }}>
                          • Trend: {category.performance.trend}
                        </Text>
                      )}
                    </View>
                  )}

                  {/* Best Practices */}
                  {category.bestPractices && category.bestPractices.length > 0 && (
                    <View>
                      <Text style={{ fontSize: 10, fontWeight: "bold", marginBottom: 6 }}>
                        Key Best Practices
                      </Text>
                      {category.bestPractices.map((practice, practiceIdx) => (
                        <Text key={practiceIdx} style={{ fontSize: 9, marginBottom: 3, marginLeft: 10 }}>
                          {practiceIdx + 1}. {practice}
                        </Text>
                      ))}
                    </View>
                  )}
                </View>
              ))}

              <View style={styles.footer}>
                <Text style={styles.pageNumber}>© {year} Keeran Networks</Text>
                <Text style={styles.pageNumber}>Page {pageNum} of {totalPages}</Text>
              </View>
            </Page>
          );
        }

        return pages;
      })()}

      {/* Outro/Conclusion Page */}
      {recommendationsData?.outro && (
        <Page size="A4" style={styles.page}>
          <View style={styles.header}>
            <Image src={logoPath} style={styles.logoBoxSmall} />
            <Text style={styles.headerTitle}>Next Steps</Text>
          </View>

          <Text style={styles.sectionTitle}>
            Top 5 AI Rocks for Next Quarter
          </Text>
          <Text style={styles.sectionSubtitle}>
            Highest-impact, easiest-to-implement priorities for the next 90 days
          </Text>

          <View style={{ marginTop: 20 }}>
            <OutroContent markdown={recommendationsData.outro} />
          </View>

          <View style={styles.footer}>
            <Text style={styles.pageNumber}>© {year} Keeran Networks</Text>
            <Text style={styles.pageNumber}>Page {4 + categoryPages} of {totalPages}</Text>
          </View>
        </Page>
      )}

      {/* Response Details Pages */}
      {(() => {
        const pages = [];
        const questionsMap = new Map(
          (survey?.questions || []).map((q: any) => [String(q.id), q])
        );

        for (let i = 0; i < answers.length; i += 10) {
          const pageAnswers = answers.slice(i, i + 10);
          const pageNum = 5 + categoryPages + Math.floor(i / 10);

          pages.push(
            <Page key={`responses-${i}`} size="A4" style={styles.page}>
              <View style={styles.header}>
                <Image src={logoPath} style={styles.logoBoxSmall} />
                <Text style={styles.headerTitle}>Response Details</Text>
              </View>

              <Text style={styles.sectionTitle}>Your Assessment Responses</Text>
              <Text style={styles.sectionSubtitle}>
                Detailed breakdown of your answers (Page {Math.floor(i / 10) + 1} of {answerPages})
              </Text>

              <View style={{ marginTop: 20 }}>
                {pageAnswers.map((answer: any, idx: number) => {
                  const question: any = questionsMap.get(String(answer.q));
                  const questionText = question?.question || `Question ${answer.q}`;
                  const category = question?.category || "General";

                  return (
                    <View key={idx} style={{ marginBottom: 12, paddingBottom: 8, borderBottom: "1px solid #E5E7EB" }}>
                      <Text style={{ fontSize: 9, fontWeight: "bold", color: "#6B7280", marginBottom: 4 }}>
                        {category}
                      </Text>
                      <Text style={{ fontSize: 10, marginBottom: 4 }}>
                        {questionText}
                      </Text>
                      <Text style={{ fontSize: 9, color: "#059669", fontWeight: "bold" }}>
                        {getAnswerText(answer.a)}
                      </Text>
                    </View>
                  );
                })}
              </View>

              <View style={styles.footer}>
                <Text style={styles.pageNumber}>© {year} Keeran Networks</Text>
                <Text style={styles.pageNumber}>Page {pageNum} of {totalPages}</Text>
              </View>
            </Page>
          );
        }

        return pages;
      })()}
    </Document>
  );
};

// Component to render outro markdown (primarily numbered lists)
const OutroContent = ({ markdown }: { markdown: string }) => {
  const lines = markdown.split(/\r?\n/).filter(line => line.trim());
  
  return (
    <View>
      {lines.map((line, idx) => {
        const trimmed = line.trim();
        
        // Check if it's a numbered list item (e.g., "1. **Title**")
        const numberedMatch = trimmed.match(/^(\d+)\.\s+\*\*(.+?)\*\*(.*)$/);
        if (numberedMatch) {
          const [, number, title, rest] = numberedMatch;
          return (
            <View key={idx} style={{ marginBottom: 12 }}>
              <Text style={{ fontSize: 10, fontWeight: "bold", marginBottom: 4 }}>
                {number}. {title}
              </Text>
              {rest && (
                <Text style={{ fontSize: 9, marginLeft: 15, fontStyle: "italic", color: "#6B7280" }}>
                  {rest.replace(/_Rationale:_\s*/, "").trim()}
                </Text>
              )}
            </View>
          );
        }
        
        // Regular paragraph
        return (
          <Text key={idx} style={{ fontSize: 10, lineHeight: 1.5, marginBottom: 8 }}>
            {trimmed}
          </Text>
        );
      })}
    </View>
  );
};

// Helper function to convert answer numeric value to text
const getAnswerText = (value: number): string => {
  const answerMap: { [key: number]: string } = {
    [-2]: "Strongly Disagree",
    [-1]: "Disagree",
    [0]: "Neutral",
    [1]: "Agree",
    [2]: "Strongly Agree",
  };
  return answerMap[value] || "Unknown";
};
