import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import { Loader2 } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { CsvQuestion, Assessment } from "@shared/types";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { getCategoryScores } from "@/lib/generateRecommendations";

interface AISuggestionsProps {
  assessment: Assessment;
  questions: CsvQuestion[];
  isActive: boolean;
}

export default function AISuggestions({
  assessment,
  questions,
  isActive,
}: AISuggestionsProps) {
  // Track if auto-generated on completion (should happen once)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(!!assessment.recommendations);
  
  // We don't need to track tab activation separately anymore, only for UI display

  // Access query client for mutations
  const queryClient = useQueryClient();

  // Check if recommendations already exist in the assessment
  const hasStoredRecommendations = !!assessment.recommendations;

  // Mutation for saving recommendations to the assessment
  const saveRecommendationsMutation = useMutation({
    mutationFn: async (recommendationText: string) => {
      const response = await apiRequest(
        "PATCH",
        `/api/assessments/${assessment.id}`,
        {
          recommendations: recommendationText,
        },
      );
      return response.json();
    },
    onSuccess: () => {
      // Invalidate queries to refresh data
      queryClient.invalidateQueries({
        queryKey: [`/api/assessments/${assessment.id}`],
      });
    },
  });

  // Either use stored recommendations or fetch new ones
  const {
    data: suggestions,
    isLoading,
    error,
  } = useQuery({
    queryKey: ["/api/ai-suggestions", assessment.id],
    queryFn: async () => {
      // If we already have recommendations stored in the assessment, use those
      if (hasStoredRecommendations) {
        return { success: true, content: assessment.recommendations };
      }

      // Calculate category scores like in the chart
      const categoryScores = getCategoryScores(assessment, questions);

      // Only make the API request if we have the needed data
      if (!categoryScores.length) {
        throw new Error("No category data available");
      }

      const payload = {
        book: "The Lean Startup",
        categories: categoryScores,
        userEmail: assessment.email || undefined,
      };

      // Call the OpenAI API to generate recommendations
      const response = await apiRequest("POST", "/api/ai-suggestions", payload);
      const result = await response.json();

      // If successful, save the recommendations to the assessment record
      if (result.success && result.content) {
        saveRecommendationsMutation.mutate(result.content);
      }

      return result;
    },
    // Only enable in two cases:
    // 1. If we already have recommendations stored (just display them)
    // 2. If the tab is active AND we haven't auto-generated before (first-time viewing)
    enabled: (hasStoredRecommendations || (isActive && !hasAutoGenerated)) && !!assessment.id,
  });

  // Show a message if tab isn't active and there are no recommendations yet
  if (!isActive && !hasAutoGenerated) {
    return (
      <div className="h-[calc(100dvh-330px)] flex items-center justify-center">
        <p className="text-muted-foreground">
          Select this tab to generate AI recommendations
        </p>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="h-[calc(100dvh-330px)] flex items-center justify-center">
        <div className="flex flex-col items-center gap-2">
          <Loader2 className="h-8 w-8 animate-spin text-primary" />
          <p className="text-muted-foreground">
            Our AI agent is working to create some actionable recommendations.
            It will be ready in a moment.
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="h-[calc(100dvh-330px)] p-4">
        <Alert variant="destructive">
          <AlertTitle>Error generating recommendations</AlertTitle>
          <AlertDescription>
            We couldn't generate AI recommendations at this time. Please try
            again later.
          </AlertDescription>
        </Alert>
      </div>
    );
  }

  return (
    <ScrollArea className="h-[calc(100dvh-330px)] rounded-md border p-4">
      <div className="space-y-6">
        <div className="markdown-text">
          <ReactMarkdown>{suggestions.content}</ReactMarkdown>
        </div>
      </div>
    </ScrollArea>
  );
}
