import PDFDocument from 'pdfkit';
import { Readable } from 'stream';

interface AssessmentData {
  id: number;
  title: string;
  score: number;
  completedOn: string;
  recommendations?: string;
  survey?: {
    title: string;
  };
}

export async function generateAssessmentPDF(assessment: AssessmentData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();
      const chunks: Buffer[] = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(24)
         .text('AI Readiness Assessment Report', { align: 'center' })
         .moveDown(1);

      // Assessment info
      doc.fontSize(14)
         .text(`Assessment: ${assessment.survey?.title || assessment.title}`)
         .text(`Completed: ${new Date(assessment.completedOn || new Date()).toLocaleDateString()}`)
         .moveDown(1);

      // Score box
      doc.rect(50, doc.y, 500, 80)
         .fillAndStroke('#f0f0f0', '#ccc');
      
      const scoreY = doc.y - 60;
      doc.fontSize(36)
         .fillColor('#059669')
         .text(`${(assessment.score / 10).toFixed(1)}/10`, 50, scoreY, { 
           width: 500, 
           align: 'center' 
         });

      doc.fillColor('black')
         .fontSize(16)
         .text('AI Readiness Score', 50, scoreY + 45, { 
           width: 500, 
           align: 'center' 
         })
         .moveDown(2);

      // Recommendations
      if (assessment.recommendations) {
        doc.fontSize(16)
           .text('AI-Powered Recommendations', { underline: true })
           .moveDown(0.5);

        doc.fontSize(12)
           .text(assessment.recommendations.substring(0, 2000), {
             width: 500,
             lineGap: 4
           });

        if (assessment.recommendations.length > 2000) {
          doc.text('\n... (continued in full report)', {
            fontSize: 10,
            oblique: true
          });
        }
      }

      // Footer
      doc.fontSize(10)
         .fillColor('#666')
         .text(`Generated by MyZone AI • Assessment ID: ${assessment.id}`, 
               50, doc.page.height - 50, { 
                 width: 500, 
                 align: 'center' 
               });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}